{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "myappv1.serviceAccountName" . }}
  labels:
{{ include "myappv1.labels" . | indent 4 }}
{{- end -}}
